spring.application.name=suits

spring.datasource.username=myuser
spring.datasource.password=secret
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.connection.pool_size=100
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.database=postgresql

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB

supabase.storage.url=https://fnezumfllsckmxbrkpgw.supabase.co/storage/v1
supabase.api.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZXp1bWZsbHNja214YnJrcGd3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDE1Nzk5NiwiZXhwIjoyMDU5NzMzOTk2fQ.5rZxGs2-lwclb8WAwybJh4k57Ngi8hGei7uXUp9edko
supabase.bucket=legal-documents